# fly.toml app configuration file generated for nexadb
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.

app = "nexadb"
primary_region = "sjc"

[build]
  dockerfile = "Dockerfile"

[env]
  DATA_DIR = "/data"
  PYTHONUNBUFFERED = "1"

[http_service]
  internal_port = 9999
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
  processes = ["app"]

[[services]]
  protocol = "tcp"
  internal_port = 6970
  auto_stop_machines = true
  auto_start_machines = true

  [[services.ports]]
    port = 6970

[[services]]
  protocol = "tcp"
  internal_port = 6969
  auto_stop_machines = true
  auto_start_machines = true

  [[services.ports]]
    port = 6969

[[vm]]
  cpu_kind = "shared"
  cpus = 1
  memory_mb = 1024

[[mounts]]
  source = "nexadb_data"
  destination = "/data"
  initial_size = "1GB"
